version: '3.8'

services:
  prismia-bot:
    build: .
    container_name: prismia-bot
    restart: unless-stopped
    volumes:
      - ./config.py:/app/config.py
    networks:
      - prismia-net
    env_file:
      - .env

networks:
  prismia-net:
    driver: bridge
